plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}
/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.10/userguide/multi_project_builds.html in the Gradle documentation.
 */

rootProject.name = "mothership"
include(":library:google")
include(":library:utils")
include(":library:http-client")

include(":library:logger")
include(":library:serialization")
include(":library:mt940")
include(":library:store")
include(":library:memoize")
include(":library:banking")
include(":library:table")
include(":library:session")
include(":library:cache")

include(":app:ledger")
